/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "Mel",
    "x": 185.78627014160156,
    "z": 2599.534423828125
  },
  {
    "name": "Rin",
    "x": 687.9830932617188,
    "z": -119.74590301513672
  },
  {
    "name": "Coffee",
    "x": 1565.21728515625,
    "z": 345.8942565917969
  },
  {
    "name": "Lillie",
    "x": 1931.8707275390625,
    "z": -14412.1728515625
  },
  {
    "name": "Grim",
    "x": 1866.26220703125,
    "z": -14414.3134765625
  }
]
