/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "Grim",
    "x": 388.4747314453125,
    "z": 59.1309928894043
  },
  {
    "name": "Mel",
    "x": 201.17941284179688,
    "z": 2606.2734375
  },
  {
    "name": "Coffee",
    "x": 197.8213653564453,
    "z": 2592.074951171875
  },
  {
    "name": "Rin",
    "x": 738.2276000976562,
    "z": -82.91023254394531
  },
  {
    "name": "Lillie",
    "x": 1872.5174560546875,
    "z": -14416.4326171875
  }
]
