/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "Rin",
    "x": 1861.014892578125,
    "z": -5465.38330078125
  },
  {
    "name": "Mel",
    "x": -5432.1962890625,
    "z": 4596.66650390625
  },
  {
    "name": "Grim",
    "x": -5427.56396484375,
    "z": 4600.0546875
  }
]
