/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "Lillie",
    "x": 436.00390625,
    "z": 184.46884155273438
  },
  {
    "name": "Grim",
    "x": 394.9692077636719,
    "z": 66.37371826171875
  },
  {
    "name": "Cai",
    "x": 401.5484313964844,
    "z": 65.49383544921875
  },
  {
    "name": "Coffee",
    "x": 2122.75732421875,
    "z": -14447.478515625
  },
  {
    "name": "Rin",
    "x": 760.772216796875,
    "z": -58.45075225830078
  },
  {
    "name": "Mel",
    "x": 697.14208984375,
    "z": 2868.56640625
  }
]
